Google Product Search&Vision API
bounswe/bounswe2020group2 pull request #106
Opened 2020-05-25 15:41 UTC by asliayk

@karalleyna and I have been working on the Google product search API. 

Our API consists of products and product sets. We've thought each brand(vendor) has its own set and customers should be able to reach these sets to see products. When the user comes to the homepage, s/he sees 11 options: 5 for customers, 6 for vendors. Here are the brief explanations for each option:

Vendor options:

- Create product set: Vendor enters set id and set name and if a set with that
id doesn't exist, a new set will be created.   
- Delete product set: Vendor enters a set id and if a set with that id exists, it will
be deleted.    
- Add product to a product set: The vendor enters product id, set id, product name, product category, product description, color and style(valid styles: home, women, men, children) to add that product to that product set.     
- Update product: The vendor enters product id, key name(“color” or “style”) and value for that key of the product to update the key value. If the key name is style but value is not equal to home, children, women or men, it warns to user to enter a valid key value.
- Delete product: The vendor enters the id of the product s/he wants to delete and product will be deleted.
- Add reference image for a product: The vendor add a picture from google cloud storage for a product by entering product id and reference image uri. S/he can add more than one picture for a product. All pictures are stored in Google cloud storage. 

Customer options: 

- List all products: Customer clicks list button to see the list of all products, the list
will be shown on a new tab.    
Output: 

![listallproducts](https://user-images.githubusercontent.com/56061820/82823657-a5201f80-9eb0-11ea-893e-ac4133818afa.jpg)

- List sets: Customer clicks list button to see the list of all sets, the list
will be shown on a new tab.   
Output:

![listsets](https://user-images.githubusercontent.com/56061820/82823712-c08b2a80-9eb0-11ea-8d5c-4a742e6ed43d.jpg)

- List products in product set: Customer enters a set id and clicks list button 
to see the list of all products in the set with that id. If a set with that id does not
exist or it is empty, it warns the user. If it exists and contains products, these 
products will be listed on a new tab.   
Output:

![listsproductsinset](https://user-images.githubusercontent.com/56061820/82823765-d698eb00-9eb0-11ea-9e05-fa8aab52d1f2.jpg)

- Filter products by category in a product set: Customer enters a set id and category(valid 
categories: apparel, apparel-v2, homegoods, toys, homegoods-v2 and packagedgoods-v1) 
and the products of that category in that set are listed on a new tab. If no product 
exists in that category or the set is empty/does not exist, it warns the user.   
Output:

![filter](https://user-images.githubusercontent.com/56061820/82823813-e6b0ca80-9eb0-11ea-83ce-6a4a2ffba825.jpg)

- List similar products: The customer can see whether there exists a similar product for a product that s/he wants to buy or look for by giving a product picture url(file path) from his/her computer, its category name, filter (ex. style=men), and list for similar products and similarity scores will be shown on a new tab as a sorted list by their scores.  
Output:

![listsimilar2](https://user-images.githubusercontent.com/56061820/82824136-6c347a80-9eb1-11ea-9140-5e134f14498f.jpg)

2020-05-25 15:42 UTC, karalleyna commented
The main purpose in choosing this Google Product Search API with @Aslı Aykan is implementing list similar products function of the image client of Google Product Search API in order to use it in the future process of Getflix. For example, a customer wants to buy a dress with specific features: its color, its style etc. She finds some dress pictures from the internet which are similar to her dream dress on her mind. However, she doesn’t have much time and doesn’t want to look all products one by one on an e-commerce web site to find some similar dresses. With this API feature, she just enters the file path of the picture and the similar products in Getflix are listed with just one click.
Other methods such as creating product set, updating product and deleting product enable the necessary environment which list similar product function uses. These methods use GET, POST,PATCH and DELETE HTTP requests rather than stuck with just GET request.
- Initially, we created a product set named cmpe352 consisting of dresses with different types and colors. 
![Product Catalog 1](https://github.com/bounswe/bounswe2020group2/blob/master/images/productCatalog1.jpg)
![Product Catalog 2](https://github.com/bounswe/bounswe2020group2/blob/master/images/productCatalog2.jpg)
![Product Catalog 3](https://github.com/bounswe/bounswe2020group2/blob/master/images/productCatalog3.jpg)
- If you want to use this product set, it is enough to give the file path of the dress image you choose.  The results will be as follows:
  - ![The dress which we have searched](https://github.com/bounswe/bounswe2020group2/blob/master/images/test_dress.jpg)
  - ![Output](https://github.com/bounswe/bounswe2020group2/blob/master/images/output.png)

- If you want to add product and its picture, just make sure that the pictures are stored on a bucket in google cloud storage and publicly readable. You should enter their google storage uri e.g.  gs://cmpe352_example/black_long_dress.jpg.

2020-05-25 16:01 UTC, MehdiSaffar commented on practice_app/package.json
> +        "util:eslint": "eslint --fix ./pages/*/.js",
Did you guys change this? If so, why?

2020-05-25 16:41 UTC, MehdiSaffar requested changes
I like the feature and I appreciate how much thought you put into it and how well you description is put out with images and test reports and so on. Good job :) 

I haven't tested the app yet as I am having trouble setting it up.
There are merge conflicts with master branch. Make sure to merge master to your branch, do the necessary code changes and push again.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getAllProducts.js
> +      .catch((err) => {
The backend shouldn't return raw HTML. I would suggest returning the a JSON for the data of the products and doing the rendering on the frontend.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getAllProducts.js
> +    // Imports the Google Cloud client library
It is enough to do `const getAllProduct = async (req, res) =>` without any explicit Promise as an `async` function is a function that returns a `Promise itself`. Also remove any `res.on('finish', resolve)` as it is not needed and simply use the regular `res.json({...})`

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getAllProducts.js
> +    var mytext = "<h1> Products </h1>";
`var` is old javascript. Use `const` for immutable variables, `let` for mutable variables.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getAllProducts.js
> +    const vision = require("@google-cloud/vision");
It is bad practice to require inside functions, you can move any require to the top level (outside of the function)

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getProductCatalog.js
> +          console.log("aaaaa");
Please remove such console logs.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getProductCatalog.js
> +          await client.createProduct(createRequest).catch((err) => {
I would suggest not mixing `async ... await` syntax with `.then(..).catch(...)`

https://css-tricks.com/understanding-async-await/

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getProductCatalog.js
> +const getProductCatalog = (req, res) =>
This function is too long. Please break it down to different functions based on request type.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getProductCatalog.test.js
> +const getProductSet = async (req) => {
This function is too long.

Also is this the actual implementation? It doesn't belong to a test file.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getProductsByCategory.js
> +    var second = str.substring(n2 + 1, str.length);
You can use const here

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getProductsInSet.js
> +
If this code is no longer necessary please get rid of this comment.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getSets.js
> +    const location = "europe-west1";
These constants appear in multiple places. This is a good fit for environment variables.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getSets.js
> +    const location = "europe-west1";
Or maybe a simple file `config.json` that is imported?

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getSets.js
> +      });
An error should be sent back as a response or the request hangs.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getSimilarProducts.js
> +    });
Please do not reinvent the wheel by trying to parse url query params yourself. This is brittle code. There are already libraries out there that do this. Try https://www.npmjs.com/package/query-string

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/api/getSimilarProducts.js
> +    });
Again please do not render like this. Use the client-side react code for proper rendering.

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/index.js
> +      )
Shorter check is 
```js
['apparel', 'homegoods', ...,  'packagedgoods-v1'].includes(document.getElementById("category-title").value)
```

2020-05-25 16:41 UTC, MehdiSaffar commented on practice_app/pages/index.js
> +      </form>
The HTML `<form>` tag is used to wrap a whole form, not a form element. It should wrap the entire form.

2020-05-26 04:10 UTC, omerfdeniz approved these changes
Your code is clean and easy-to-read with explanatory comments. I see that you paid attention to not making http requests in unit tests, which is important for preventing future unexplainable errors. You should also remove console logs created for testing purposes before merge. All in all, I found your work pretty useful and demanding. The functionalities you provide with this api is essential for our product. If you can make the stated improvements to the code, it will be better in the long run, but even right now code is working properly. Excellent job!

2020-05-27 13:14 UTC, asliayk commented
- [x]	Unnecessary comments and console.log’s are removed, var is changed to let.
- [x]	We used shorter checks with includes.
- [x]	We broke our main function(getProductCatalog) into smaller functions based on their types(create, delete or update)
- [x]	We removed res.on and used res.json instead.

2020-05-27 13:15 UTC, karalleyna commented
- [x]	We wrote our frontend part as a separate js file and stored in components folder. (SimilarProduct.js)
- [x]	Since we updated our code, we recreated our unit tests.
- [x]	We updated our listing similar products feature, similar products are shown on the same page, not on a new tab now. 
- [x]	We updated GetSimilarProducts.js file with the help of @MehdiSaffar , user can choose a picture on his/her computer now, s/he does not need to give its file path anymore.

2020-05-27 15:30 UTC, MehdiSaffar commented
I merged master correctly by taking the most up to date version of it.
I refactored a few things.

I will accept this pull request. 

Good job guys :)

2020-05-27 15:30 UTC, merged