[FRONTEND] Refactor init, categories, search, product card, login, signup, routes, mocks...
bounswe/bounswe2020group2 pull request #298
Opened 2020-12-22 22:43 UTC by MehdiSaffar

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Description

### Remove race condition with /init

I made it so that /init and /categories loads first before the app itself uses those values. This solves the shopping cart attempting to load before /init finishes.

### Request interceptor defined in api.js instead

Easiest and safest way to always have the most up to date token value in localStorage.

### Loading screen

While the app is loading, shows the getflix logo over white background with 2s fade-in animations. Loading spinner starts only after 3s

### Categories and subcategories

- Categories are now dynamically loaded from backend during init and stored in app context
- Refactored all components that depend on categories to work with this
- Removed old categories from utils.js
- Search side panel now actually changes subcategories based on currently selected category

### Search page

- Fixed products not loading because of wrong `products` key placement in JSON returned from backend.

### Product card

- Fixed NaN showing on discounted price

### Shopping cart page

- Made product pictures clickable, brings to product page
- Fixed vendor.name being passed to link of vendor instead of vendor.id

### Profile

- Fix last name not showing in avatar
- Fix last name not showing in profile page

### Login/Signup

- Removed mock delay
- Add proper setLoading with try and finally

### Routes

- Protect routes based on user type (guest, customer, vendor)
- Add proper redirect when wrong url typed

### Mocks

- Add mock for /init
- Add mock for /categories
- Add warning on development environment showing how many active mock handlers are active (to prevent mistakes)
- All mocks are deactivated in this PR

# Screenshots

### Loading screen
![image](https://user-images.githubusercontent.com/13124263/102939601-97229380-44bf-11eb-86bf-156143dfbe04.png)

### Last name showing properly
![image](https://user-images.githubusercontent.com/13124263/102939637-aa356380-44bf-11eb-9fcc-795dd0d60820.png)
![image](https://user-images.githubusercontent.com/13124263/102939663-b7525280-44bf-11eb-9866-eca77c506bf1.png)

### Product card NaN fix
![image](https://user-images.githubusercontent.com/13124263/102939750-e5d02d80-44bf-11eb-81ff-af1332df72f0.png)

# Test results

Please run all the tests and dump the result/summary here in a code block.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Potential problems/Important remarks

- Added warning comment in profile page about the name of the key being surname instead of lastname

closes #297 #296 #295 #294 #293

2020-12-23 00:22 UTC, abdullahyldz requested changes
I reported some bugs and corrected two small bugs.
Very useful improvements to project.

2020-12-23 00:22 UTC, abdullahyldz commented on ecommerce/frontend/src/components/product_card/ProductCard.js
> +    console.log(product)
In the Cell Phones and Accessories subcategory, there returns 2 items like this 
![image](https://user-images.githubusercontent.com/44057640/102943077-1a47e780-44c8-11eb-9b94-bd4d36f60763.png)
Their passed fields in the ProductCard is like this:
```
Object
currency: "TL"
id: 22
imageUrl: undefined
price: 799.9
price_after_discount: 703.912
rating: 0
title: "Los Angeles Lakers Home"
__proto__: Object
```

```
Object
currency: "TL"
id: 26
imageUrl: "/image/3"
price: 799.9
price_after_discount: 703.912
rating: 0
title: "Los Angeles Lakers Home Jersey"
__proto__: Object
```

I think,  second imageUrl is the `new format `Backend sends us such that we append it after Backend URL. Other image URLs are just correct. Can you make sure?

2020-12-23 00:22 UTC, abdullahyldz commented on ecommerce/frontend/src/components/product_card/ProductCard.js
> +    console.log(product)
Also, another problem is same item is returned again with the same query.

![image](https://user-images.githubusercontent.com/44057640/102943305-b114a400-44c8-11eb-9d7c-0f53c8adf61e.png)

2020-12-23 00:22 UTC, abdullahyldz commented on ecommerce/frontend/src/components/pages/SearchPage.js
> +// import { categories, subcategories } from '../../utils'
[SOLVED] Clicking the main category does not properly set URL with category ID. 
Solved it in commit : ad4bda3

![image](https://user-images.githubusercontent.com/44057640/102943422-0ea8f080-44c9-11eb-9826-4196ada10319.png)

2020-12-23 00:22 UTC, abdullahyldz commented on ecommerce/frontend/src/components/pages/SearchPage.js
> +// import { categories, subcategories } from '../../utils'
Thus, breaks the Backend with 500 (Internal Error)

2020-12-23 00:22 UTC, abdullahyldz commented on ecommerce/frontend/src/components/layout/Content.js
> +                <Redirect to="/" />
These were needed, thanks.

2020-12-23 09:34 UTC, MehdiSaffar commented on ecommerce/frontend/src/components/product_card/ProductCard.js
> +    console.log(product)
@abdullahyldz two of products returned from backend have an empty images array, and one with `/image/3`. 

![image](https://user-images.githubusercontent.com/13124263/102982149-21e4ac00-451b-11eb-8c61-162b76f65a07.png)


Product should never be allowed not to have pictures.

For `/image/3` I guess we need to prefix ourselves. I will see what I can do about that

2020-12-23 10:00 UTC, MehdiSaffar commented
fixes #300 

![image](https://user-images.githubusercontent.com/13124263/102984219-5148e800-451e-11eb-9db9-e01492867773.png)

also fixed image not showing by prefixing with apiUrl

2020-12-24 17:25 UTC, MehdiSaffar commented
Integrated all changes, merging

2020-12-24 17:25 UTC, merged