Adding Vendor Details Endpoint
bounswe/bounswe2020group2 pull request #390
Opened 2021-01-16 21:27 UTC by bcetin

2021-01-19 11:23 UTC, bekir96 reviewed
Can you add serializer for vendor_details response? It makes our code mechanism more robust.

2021-01-19 11:27 UTC, bekir96 reviewed
And also can you increase label number to better understand what is done at first sight

2021-01-19 11:35 UTC, bekir96 requested changes
Can you resolve conflict

2021-01-19 17:58 UTC, omerfdeniz commented on ecommerce/backend/API/views/vendor.py
> +    vendor = Vendor.objects.filter(id=vendor_id).first()
please check whether that vendor really exists and return 400_BAD_REQUEST if it does not.
```suggestion
    vendor = Vendor.objects.filter(id=vendor_id).first()
    if vendor is None:
        return Response(status=status.HTTP_400_BAD_REQUEST)
```

2021-01-19 17:59 UTC, omerfdeniz commented on ecommerce/backend/API/views/vendor.py
> +    vendor = Vendor.objects.filter(id=vendor_id).first()
don't forget to delete debug comments also

2021-01-20 15:16 UTC, omerfdeniz requested changes
Please check the availability of the vendor

2021-01-21 12:30 UTC, merged