[BACKEND] Notification Manager and Get Notifications Endpoint
bounswe/bounswe2020group2 pull request #426
Opened 2021-01-22 16:47 UTC by umutoksuz

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Description

Below mentioned tasks are done to implement notification system:
- Models are added for  notifications
- A function is created to populate a notification whenever order status of a purchase changes
- A function is created to populate a notification when price change event occurs
- An endpoint to get notifications of a user
- Tests for notification system 
 

# Test results

```
System check identified no issues (0 silenced).
....................................................................
----------------------------------------------------------------------
Ran 68 tests in 5.453s

OK
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have checked my code and corrected any misspellings
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-01-22 21:33 UTC, furkannane approved these changes
Changes are appropriate.

2021-01-22 22:16 UTC, omerfdeniz commented on ecommerce/backend/API/tests/test_notification.py
> +        self.assertNotEqual(notification, None)
Please check the status code and response in your tests. Also do not forget to adhere to our response convention in manage_notifications()
```suggestion
        self.assertNotEqual(notification, None)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["status"]["successful"], True)
```

2021-01-22 22:20 UTC, omerfdeniz commented on ecommerce/backend/API/tests/test_notification.py
> +        self.assertNotEqual(notification, None)
Please also test having no notification when a PUT request with the same price is sended

2021-01-22 22:21 UTC, omerfdeniz requested changes
Please check the response add the test provided in the comment

2021-01-23 01:23 UTC, bekir96 approved these changes
All test results looks good and migration handling is correct, you can merge

2021-01-23 10:07 UTC, omerfdeniz approved these changes
Great work, now you can merge

2021-01-23 10:09 UTC, merged