Reddit branch merge
bounswe/bounswe2020group2 pull request #91
Opened 2020-05-23 15:19 UTC by bcetin

2020-05-23 20:53 UTC, MehdiSaffar commented
- There is no description. Please look at the previous pull requests to know the format
- Did you actually run the tests before submitting this pull request? Just looking at the code I know that it won't pass.
- One test is not enough
- Do not make HTTP requests inside the unit tests as they slow down the entire unit test suite. 
- There is a lot of whitespace all over the place. Please format your code before submitting. Use `npm run util:prettier` for that from the command line.
- There is a lot of code duplication for the posts part, both in the render and inside the route. I showed you on Slack how to use `Array.map`. Please use that.

2020-05-23 21:51 UTC, asliayk commented
- The countries that doesn't have reddit info returns nothing. I think it would be better if it informed the user like "no info for that country", as in Furkan's covid API, or maybe as an alert.
- I couldn't run your test as Mehdi couldn't. Maybe you installed something and ran the test after that.

2020-05-23 22:02 UTC, karalleyna requested changes
- If the end user chooses somewhere,e.g Black Sea,Atlantic Ocean etc., instead of a country by mistake, the program gives 
`Unhandled Rejection (TypeError): Cannot read property 'name' of undefined`. This can be handled by adding if statement which checks whether countryName is undefined or not after you get the countryName.
- The test does not work properly and it can be better if you use the module which you export in order to test.

2020-05-23 22:09 UTC, asliayk reviewed
- The countries that don't have reddit info returns nothing. I think it would be better if it informed the user like "no info for that country", as in Furkan's covid API, or maybe as an alert.
- I couldn't run your test as Mehdi couldn't. Maybe you installed something and ran the test after that.

2020-05-24 09:19 UTC, MehdiSaffar requested changes
(Ignore this comment)

2020-05-24 18:20 UTC, ozdenizdolu approved these changes
I believe @asliayk  @karalleyna and  @MehdiSaffar has covered almost everything. Here are my comments. I approve the merge and leave considering my comments to you.

2020-05-24 18:20 UTC, ozdenizdolu commented on practice_app/pages/api/getRedditData.test.js
> +describe('checkGetRedditData', () => {
I think existing tests are good tests but I suggest you also add some tests for a malformed input data. If I understand it correctly, you check `getPostData` function for a well formed json input in `./exampleRedditData.json`. Maybe you can add 2-3 more cases where different parts of the input is malformed or missing.

2020-05-24 18:20 UTC, ozdenizdolu commented on practice_app/pages/api/getRedditDataModule.js
> +    var outJSON = []
Not a big deal but, I believe using `var` keyword is outdated when declaring variables. You should use `let` and  instead.

2020-05-24 19:07 UTC, merged

2020-05-24 19:34 UTC, vaveylafv commented
Some country names gathered from getLocationInfo causes problems when given to reddit api. Like 'United States' causes {"message": "Not Found", "error": 404} for reddit. It must be converted to 'USA' before passing to reddit.